Run all cells marked `In [ ]` using the [$\blacktriangleright$ Run] button above and **think about the result you see**.
Be sure to do all exercises (in blank cells) and run all completed code cells. 

If anything goes wrong, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart). Or run text cells to get the formatted text back from markdown.

---

# Numerical Arrays

You have now seen the basic Python language (_"syntax"_) and programming methods.  
These basic building blocks can be built-up to construct advanced programs for things such as:
* solving the equations for engineering problems;
* simulating the behaviour of constructions and other designs;
* optimising structures, energy flows or other problems;
* analysing data from measurements in order to present the results.


## General advice on independent learning:

New functions new methods of manipulating data will be introduced as they are needed.
* **Keep a file or notebook** to make a note of the most useful functions and methods for you to look up when you need them, as it is impossible to remember everything.
* For things you use less frequently **look them up on the internet** or in the manuals by searching for what you want to do and the keywords "Python" or "NumPy" along with any other snippets you remember. 
    * Most programmers consult the online guides frequently.

## Importing Modules and Accessing Attributes

In order to manipulate numerical data effectively we need to use a new data type called a numerical `array`.  
These can be used more mathematically than lists and behave a little differently.  

Arrays and plotting functions are imported from external libraries, in the same way we have already seen for the `math` library.

## Numpy and Numerical Arrays

Lists are useful but it can be fiddly to perform mathematical operations for each element, e.g.::

```python 
b = [3*sin(x)**2+10 for x in a]
```

Also multiplying a list by a number is interpreted as adding the list to itself that number of times:

```python
alist = [1, 2, 3]
print(alist+alist)
print(alist*3)
```
> Output:
```
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
```


Another data type can be imported with the Numerical Python (NumPy) module that behave in a more mathematically logical way.  

### Numpy

NumPy is a Python library that provides efficient operation on arrays of data.  
NumPy stores data in what are called *numerical arrays*, along with many functions for generating and methods for manipulating them.

It is usually imported using the alias `np`:
```python
import numpy as np
```
You can then get help by using the `help(MODULE.THING)` command, for example type:
```python
help(np.random)
```
To see the help manual on the `random` functions in NumPy.  

### Converting Lists to Arrays

An array *looks* like a `list` but it is a NumPy N-Dimensional Array (in this case 1D).  

NumPy arrays have element-by-element (_elementwise_) operations, which is more logical mathematically:

In [1]:
import numpy as np

alist = [1, 2, 3, 4]
ary = np.array(alist)

print(ary+ary)
print(ary*ary)
print(ary**3)

[2 4 6 8]
[ 1  4  9 16]
[ 1  8 27 64]


Plotting can be done on arrays the same as with lists:

* NumPy also contains functions that can act directly on all the elements of an array (unlike those in the `math` library`)

### Generating Arrays with `arange()`

NumPy can generate arrays directly using the function `arange()`:

In [2]:
import numpy as np

a = np.arange(1, 8)
print(a)
print(a**2)

[1 2 3 4 5 6 7]
[ 1  4  9 16 25 36 49]


The `arange` function can also use fractional values 

The syntax is `range(VAR1,VAR2,STEP)`, where the  values created are those between `VAR1` and `VAR2`, including `VAR1` but not `VAR2`:

In [3]:
import numpy as np

a = np.arange(-1, 1, 0.5)

print(a)

[-1.  -0.5  0.   0.5]


**Note:** the second  value is not included in the array, so to get around this the value needs to be slightly above the required end-point.

#### Exercise: Create an array that goes from `-2` to `2` in steps of `0.2` and _includes_ the numbers `-2`, `0` and `2`

In [5]:
# YOUR CODE HERE


[-2.0000000e+00 -1.8000000e+00 -1.6000000e+00 -1.4000000e+00
 -1.2000000e+00 -1.0000000e+00 -8.0000000e-01 -6.0000000e-01
 -4.0000000e-01 -2.0000000e-01 -4.4408921e-16  2.0000000e-01
  4.0000000e-01  6.0000000e-01  8.0000000e-01  1.0000000e+00
  1.2000000e+00  1.4000000e+00  1.6000000e+00  1.8000000e+00
  2.0000000e+00]


Expected result:
```
[-2.0000000e+00 -1.8000000e+00 -1.6000000e+00 -1.4000000e+00
 -1.2000000e+00 -1.0000000e+00 -8.0000000e-01 -6.0000000e-01
 -4.0000000e-01 -2.0000000e-01 -4.4408921e-16  2.0000000e-01
  4.0000000e-01  6.0000000e-01  8.0000000e-01  1.0000000e+00
  1.2000000e+00  1.4000000e+00  1.6000000e+00  1.8000000e+00
  2.0000000e+00]
```

**Note:** Sometimes the `arange` function returns the values in scientific notation, as above.

This is due to the central value being _very close_ to zero but not quite (due to precision accuracy).

One solution to this is to use the `.round()` function method built in to arrays:

In [6]:
import numpy as np
a = np.arange(-2, 2.1, 0.2)

print(a.round(1))

[-2.  -1.8 -1.6 -1.4 -1.2 -1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6
  0.8  1.   1.2  1.4  1.6  1.8  2. ]


### Generating Arrays with `linspace()`

The `arange` function is useful when we want an array of numbers with a fixed spacing.
However, in some applications we might want an array that starts and ends at fixed values but has a certain *number* of steps in between.

For this we can use the `linspace` function from NumPy, which stands for *"linear spacing"*.  
Type `help(np.linspace)` to read more about it:

In [7]:
import numpy as np
pi = np.pi

a = np.linspace(-pi, pi, 5)
print(a)

[-3.14159265 -1.57079633  0.          1.57079633  3.14159265]



This has returned 5 values in total, including **both** the start value $-\pi$ and end value $\pi$.  
That is, with `x=linspace(a,b,n)` $a \leq x \leq b$ (unlike with `x=arange(a,b,dx)` where $a \leq x < b$).  

Both `linspace` and the previous `arange` function are very useful when plotting mathematical functions.

## 2D Arrays and Numpy N-D arrays

[http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

There are various ways to create an array, including converting from a *list*, entering all the values by hand, or generating large arrays using special functions and loops. We can also change the individual values in arrays.

Study the following examples and practice changing things and looking at the outputs to understand how things work.

### Converting from a list to an array

If we have all the values in a (nested) list it can be converted to a numerical array:

In [8]:
import numpy as np

mylist = [[1,2,3],[4,5,6],[7,8,9]]

myarray = np.array(mylist)

print(myarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


An array has a *dimension* and a *shape*:

In [9]:
print(myarray.ndim)
print(myarray.shape)

2
(3, 3)


This means it is a 2 dimensional array, with 3 rows and 3 columns.

### Accessing array values by index

We can also access the elements of *square arrays* using indexing: `arrayname[row,col]`, where the variables `row` and `col` are replaced by the values of the row and column number we want to access.

In [10]:
print(myarray[0, 2])

3


Print the middle number in the block (5).

In [ ]:
# myarray[?, ?]
# YOUR CODE HERE


Print the last number in the block (9)

In [ ]:
# YOUR CODE HERE


To change a value

In [ ]:
myarray[1, 1] = 111

print(myarray)

### Manipulating numerical arrays

[http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)

### Generating Arrays using Special Functions


In [11]:
nrows = 5
ncols = 7
dimensions = (nrows, ncols)
myzeros = np.zeros(dimensions)
print(myzeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Try using different numbers for the parameters in these functions to see what happens.

In [12]:
myones = np.ones((3,5))
print(myones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
from numpy.random import random
dims = (5, 2)
rands = random(dims)
randr = rands.round(2)
print(randr)

Shorthand notation can also be used:
```python
myzeros = np.zeros((nrows,ncols))
```

We can take *slices* of an array using the notation `arrayname[ROWSLICE, COLSLICE]`, where `ROWSLICE` and `COLSLICE` use the same slicing rules `STARTAT:ENDBEFORE` as seen in previous sections. 

For example we can slice off a single row or column:

The code below does the following:

1. Create an array of ones using the `numpy.ones` function with one column and five rows.
2. Change the middle value to 5.
3. slice the column into the middle column of an array of $5\times7$ zeros.

In [13]:
myones = np.ones((5,1))
print(myones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [14]:
myones[2] = 5
print(myones)

[[1.]
 [1.]
 [5.]
 [1.]
 [1.]]


In [15]:
newarray = np.zeros((5, 7))

newarray[:, 3] = myones[:, 0]
print(newarray)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


* Note that `myones` is a 2D array so we have to slice all values `:` in column `0` using `[:, 0]`

Further reading can be found [here](https://docs.scipy.org/doc/numpy/user/quickstart.html).

## Vector and Matrix mathematics

You will learn about vectors and matrices later in the maths section of this course. Numerical arrays can also be used to perform vector and matrix calculations.

**Come back to this section later in the semester when you need it!**

Note that there are different ways of multiplying vectors (and hence arrays)

With $\vec a = [a_1, a_2, a_3, \cdots]$  
and $\vec b = [b_1, b_2, b_3, \cdots]$

### Elementwise multiplication

$ [a_1 b_1, a_2 b_2, a_3 b_3, \cdots ]$

In [16]:
# element by element multiplication
a = np.array([1,2,3,5])
b = np.array([2,4,6,8])

print( a*b )

print( np.multiply(a, b) ) #alternative method

[ 2  8 18 40]
[ 2  8 18 40]


### The scalar dot product

$ \vec a \cdot \vec b = a_1 b_1 + a_2 b_2 + a_3 b_3 + \cdots$

In [17]:
# dot product on arrays
a = np.array([1,2,3,5])
b = np.array([2,4,6,8])

print( a@b )

print( np.dot(a, b) ) #alternative method

68
68


### The vector cross product

$$\vec a \times \vec b
=
\begin{pmatrix}
a_2 b_3 - a_3 b_2 \\
a_3 b_1 - a_1 b_3 \\
a_1 b_2 - a_2 b_1
\end{pmatrix}$$

In [18]:
# cross product on arrays
x = [1, 2, 3]
y = [4, 5, 6]

print( np.cross(x, y) )

[-3  6 -3]


## Matrices

http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

A further extension to 2D arrays is doing matrix algebra using NumPy. This uses the .linalg library within NumPy
http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

Linear algebra functions work OK on arrays, but it is often better to use the numpy.matrix data type.
Matrices can be created and manipulated in similar ways to 2-D arrays, or converted from arrays to matrices.

In [19]:
from numpy import linalg
import numpy as np

a1=np.arange(1,5)
#a1 = [1 2 3 4]

a2=a1.reshape(2,2)
#a2 = [[1 2]
#      [3 4]]


M = np.matrix(a2)

M

matrix([[1, 2],
        [3, 4]])

Numpy matrices have special operations, including handling column vectors and proper matrix multiplication.

### Row and column vectors
A column vector can be created by transposing a row vector:

In [20]:
rvec = np.matrix(range(1,5))

print(rvec)

[[1 2 3 4]]


In [21]:
cvec = rvec.transpose()

print(cvec)

[[1]
 [2]
 [3]
 [4]]


Note that slicing a column from a matrix results in a column vector, which can then be multiplied in the usual way:

In [22]:
v = M[0,:] #row 0, all column entries `:` 

print(v)

[[1 2]]


In [23]:
w = M[:,0] #all row entries `:`, column 0 

print(w)

[[1]
 [3]]


### Vector Multiplication

The order you multiply vectors is important.

In [24]:
c=v*w

print(c)

[[7]]


In [25]:
d=w*v

print(d)

[[1 2]
 [3 6]]


Note that the `*` operator does the dot product for matrix type data (**different to regular NumPy arrays**)

In [26]:
a = np.matrix([1,2,3])
b = np.matrix([4,5,6]).transpose()

print(a)
print(b)

[[1 2 3]]
[[4]
 [5]
 [6]]


In [27]:
print( a*b )

[[32]]


### Elementwise multiplication of a Matrix

Vectors have to have the same dimensions

In [28]:
a = np.matrix([1,2,3])
c = np.matrix([4,5,6])

print( np.multiply(a, c) )

[[ 4 10 18]]


In [29]:
# Work out what's going on here...

a = np.matrix([1,2,3])
b = np.matrix([4,5,6]).transpose()

print( np.multiply(a, b) )

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


### Dot (scalar) and Cross (vector)  product 

Note that the functions only accept very specific orientations for the vectors,  
and can be confusing.

In [30]:
#row vector
a = np.matrix([1,2,3])

#column vector
b = np.matrix([4,5,6]).transpose()

#row vector
c = np.matrix([4,5,6])

#np.dot has to be a row and column
print( np.dot(a, b) )

#np.cross has to heve the same dimensions!
print( np.cross(a, c) )

[[32]]
[[-3  6 -3]]


### Matrix multiplication

http://www.mathsisfun.com/algebra/matrix-multiplying.html

Notice the difference between the folowing two cases:

In [31]:
print(a2*a2)
print()
print(M*M)

[[ 1  4]
 [ 9 16]]

[[ 7 10]
 [15 22]]


### Inverse Matrices

In [32]:
M_inv = linalg.inv(M)
print(linalg.det(M)) #check the determinent is not zero (or within numerical error of 0)
print(M_inv)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


This can be used to solve systems such as:  
$M\vec x = \vec v$

i.e., to solve for $\vec x$:  
$\vec x = M^{-1}\vec v$

In [33]:
m=np.matrix("6,-5,0; 2,3,6; -2,2,-1") #this is another way of making a matrix
v=np.matrix("1; 2; 3") #semicolons separate the rows
print(m)
print(v)

[[ 6 -5  0]
 [ 2  3  6]
 [-2  2 -1]]
[[1]
 [2]
 [3]]


In [34]:
m_inv = linalg.inv(m)
print(linalg.det(m))
x = m_inv*v
print(x)

-40.000000000000014
[[ 2.875]
 [ 3.25 ]
 [-2.25 ]]


Use this to check your answers to the Maths problems later in the course!

### Eigenvalues and eigenvectors

http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html

In [35]:
My = np.eye(3) #the identity matrix

print(My)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
My[1,0]=My[0,1]=1

print(My)

[[1. 1. 0.]
 [1. 1. 0.]
 [0. 0. 1.]]


In [37]:
evals,evecs = linalg.eig(My)

print(evals)

print(evecs)

[2. 0. 1.]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [38]:
for i in range(3):
    print("Eigenvalue", evals[i], "has eigenvector", evecs[:,i])

Eigenvalue 2.0 has eigenvector [0.70710678 0.70710678 0.        ]
Eigenvalue 0.0 has eigenvector [-0.70710678  0.70710678  0.        ]
Eigenvalue 1.0 has eigenvector [0. 0. 1.]


### Exercise (later in the course): Do the exercises from your Maths problems to check the answers and understand how these functions work.


The help manual below can be used for more information:

In [39]:
help(linalg.eig)


Help on _ArrayFunctionDispatcher in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    A namedtuple with the following attributes:
    
    eigenvalues : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    eigenvectors : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``eigenvectors[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``eigenval